version: "3.3"
services:
  postgres:
    container_name: postgres-infiazure-pms-container
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: infiazure_pms
    # ports:
    #   - 5432:5432
    networks:
      - new-network
    restart: always
    expose:
      - 5432
    # volumes:
    #   - postgres:/data/db

  backend:
    container_name: infiazure-pms-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      APP_PORT: 3000
      DATABASE_HOST: postgres-infiazure-pms-container
      DATABASE_PORT: 5432
      DATABASE_NAME: infiazure_pms
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
    networks:
      - new-network
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

networks:
  new-network:
    driver: bridge
